[build]
  command = "npm run build"
  publish = "build"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  timeout = "30s"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 