[build]
  command = "npm run build"
  publish = "build"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[functions]]
  external_node_modules = ["openai"]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 